### PR TITLE
crop logo title to make favicon. link to favicon in head

### LINKED ISSUE #54: Favicon Missing
The openoakland website doesn't have a favicon

### PR DESCRIPTION
**Pull request by TangoYankee**
**Issue**  
Closes #54 

**Description**  
1. Create a cropped version of the logo title where the text is removed and it is 'squared'
2. Use this cropped copy as the favicon. 
3. Create a reference in the head to the favicon image.

### CODE REVIEW

**Comment by rahulkgupta** [comment]
Would it be possible to add more folks who can approve reviews?

**Comment by ckingbailey** [comment]
You want to be able to review @rahulkgupta? I think I can make that happen.

**Comment by rahulkgupta** [comment]
I would love to get access @ckingbailey

**Comment by TangoYankee** [comment]
woo!

**Pull request merged**
