### PR TITLE
Add speaker series to /calendar

### LINKED ISSUE #106: Update /calendar page to remove guest speaker and add upcoming dates
## Description
Our current calendar page is out of date and doesn't have any details about the recurring meetings that happen each month, making it difficult for people to engage with important OO-related events like steering committee.

## Proposed content 

- [x] Remove 9/22 speaker info.
- [x] Add the following:

### Join us every Tuesday on Zoom
- We meet every Tuesday, 6:30-9:00
- [RSVP on Meetup](https://www.meetup.com/OpenOakland/events/) to get the Zoom link
- We welcome folks of all skill levels! 
_Normally, we meet in City Hall but will be fully remote during the pandemic._

**Recurring meetings**
The following events happen during hack night on the following dates:
- First Tues of each month: Demo Night (project previews!)
- Third Tues of each month: Steering committee meeting (open to all members; agenda is posted 1 week prior in #leadership on Slack)
- Last Tues of each month: member orientation

### Past events
- [National Day of Civic Hacking 2020](https://docs.google.com/document/d/17_0O4QRnFS705npB-bo4xuLtfJHGF5yAdNdd2HMe5SI/edit?usp=sharing)
- [Open Data Day 2019: Public Records Requests](https://www.meetup.com/OpenOakland/events/258831439/)
- [Day of Service 2019](https://www.eventbrite.com/e/openoakland-day-of-service-2019-tickets-59979544432#) in support of local Oakland organizations
- [National Day of Civic Hacking 2019: Record Clearance and Know Your Rights](https://www.eventbrite.com/e/national-day-of-civic-hacking-2019-tickets-69928206147#)

## If you are working on this issue, consider the following ongoing issues:
- [x] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

### PR DESCRIPTION
**Pull request by theecrit**
Closes #106 

## /calendar updates
- Hack night copy updated with more compelling CTA
- Regular monthly meeting details added
- Past events restyled to be more engaging using Bootstrap card format
- Jumbotron include added to enable election announcement

### Screenshots
- [20201111-Desktop](https://user-images.githubusercontent.com/32755410/98889942-c7522d80-244f-11eb-959d-94b52ceab550.png)
- [20201111-Mobile](https://user-images.githubusercontent.com/32755410/98889954-cc16e180-244f-11eb-84e2-4fc8ac5b1905.png)

## /about-us updates
- Added election announcement

### Screenshots
- [20201111-AboutUs-Desktop](https://user-images.githubusercontent.com/32755410/98890023-ecdf3700-244f-11eb-9927-dcd726c932af.png)
- [20201111-AboutUs-Mobile](https://user-images.githubusercontent.com/32755410/98889995-de911b00-244f-11eb-9d2c-b31fb9a36c22.png)

##
- I'd love to make the event tiles run horizontally, then vertically, as in a mosaic. However, I believe the only way to do that using Bootstrap in Jekyll requires javascript, which is beyond my capabilities at this stage. If someone else wants to take a crack, I recommend opening a separate issue. Design-wise, I tested a full-width tile on desktop but it's so huge it makes scanning the full list of events unwieldy.

### CODE REVIEW

**Comment by ckingbailey** [comment]
@theecrit do you have access to CircleCI so you can see what tests are failing?

**Comment by theecrit** [comment]
@ckingbailey Yes, and it's similar to something I encountered w/ projects page. I have the event card html wrapped in a div w/ an "event" ID; when the include loops the event instantiations from the md file, it repeats that same ID in the html, causing the error (repeating ID in the generated html).

I have a couple of ideas for how to fix it that I'll test out tomorrow but so far everything I've tried has been a no-go (pulling the ID attribute from the html messes w/ the formatting, for example, because of the way I have the css set up).

**Comment by theecrit** [comment]
@ckingbailey Ok, I've managed to get the tests passing. But there seems to be a phantom `</div>` tag floating below the jumbotron on the /calendar page that I cannot for the life of me identify in the actual code.

**Comment by ckingbailey** [comment]
I think the phantom `<p></div></p>` is a Jekyll issue arising from mixing markdown and html. I didn't dig into it too much, but I noticed that Jekyll thinks the `"announcement"` jumbotron is part of the `"recurring-meetings"` list. It looks like when Jekyll interprets the end of the list being after the jumbotron, it captures the closing `<div>` tag of the announcement element in the otherwise empty `<p>` that it wants to insert below the list.

I've got a god awful little hack to force Jekyll to understand that the jumbotron is not part of the list. I added a single line containing only a zero-width space, `&#8203;`, right above the jumbotron. The drawback, other than the fact that some unsuspecting contributor is sure to break this icky little hack in the future, is that Jekyll instead adds an empty `<p>` _above_ the jumbotron, messing up the vertical spacing of the layout.

I think this might be related to [newlines being ambiguous and troublesome in markdown in general](https://gist.github.com/shaunlebron/746476e6e7a4d698b373).

```markdown
- **Last Tuesday of each month**  
New member orientation: Get a personal introduction to OpenOakland.

&#8203;
{% for announcement in site.data.announcement %}
  {% include announcement.html %}
{% endfor %}

## Past Events
```

### Screenshot showing vertical spacing change

Screen Shot 2020-11-15 at 5 50 53 PM

**Comment by ckingbailey** [comment]
I've got a slightly better hack. I inserted a [kramdown comment](https://kramdown.gettalong.org/syntax.html#extensions) right above the announcements for-loop. This way, Jekyll understands that the list is done, it does not insert any extra content for the newline, and we can leave a helpful comment as to why the comment is there—a meta-comment, if you will 😉.

Shoutout to [this SO answer](https://stackoverflow.com/a/42323390) for the workaround.

```markdown
- **Last Tuesday of each month**  
New member orientation: Get a personal introduction to OpenOakland.

{::comment}
This comment element is here to "trick" Jekyll's markdown parser, called kramdown, into closing the above list without inserting any content between the list and the next element
{:/comment}
{% for announcement in site.data.announcement %}
  {% include announcement.html %}
{% endfor %}

## Past Events
```

**Comment by theecrit** [comment]
@ckingbailey That is some serious sleuthing! Thank you - works like a charm! Shall I merge?

**Review by Deckert — APPROVED** [review]
I'm not able to review this super thoroughly at the moment. At a glance it looks great.

**Pull request merged**
