### PR TITLE
Add project filter dropdown

### LINKED ISSUE #126: Add filter to /projects page
## Description
Currently, all projects are essentially listed in one long column, making it hard to identify relevant projects. We'd like to add some method of organization/filtering to enable readers to identify projects that best fit their interests.

## Potential solution
See: https://github.com/openoakland/openoakland.org/issues/55#issuecomment-721514034

### Taxonomy
Any filters will require a tagging taxonomy. Basic taxonomies currently in use (in Hack Night intro deck; note lowercase capitalization style) includes:

**Type**
- openoakland
- open data
- community services

**Topic**
- arts
- education
- environment
- budgeting
- campaign finance
- city council
- food security

A third taxonomy would be the one already in use in the page nav, which should probably be updated to:

**Status**
- Ongoing
- Active
- Dormant
- Complete
- Decommissioned

While taxonomies could stand to be revisited, this is not within the scope of this issue.

### Layout and behavior

- Recommendation: default view to "Active" projects, rather than all.

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

### PR DESCRIPTION
**Pull request by robdodson**
**Note**: This is still a work in progress and not ready to merge, but folks can play around with it and comment on the code.

closes #126

##### _Please describe the changes this PR makes_

- Adds a little snippet so pages can conditionally include scripts. This way the project filter is only loaded on the /projects page.
- Adds a `data-tags=""` attribute to every project card element. This should be a comma separated list of tags.
- Adds a [custom element](https://developers.google.com/web/fundamentals/web-components/customelements) named `<project-filter>` which wraps the project cards and renders a dropdown for filtering the cards by tags. This element could render more than one dropdown if we wanted to include additional categories (stack, topics, etc). Right now it only has one dropdown which filters projects by their status (ongoing, active, inactive, decommissioned).

👉 I ended up removing a lot of the copy on the existing /project page as I was prototyping. Definitely open to ideas for where this content should go 🤔

### Mobile screenshots
image

<br>

### Desktop screenshots
image

### CODE REVIEW

**Comment by theecrit** [comment]
This looks really good to me. A couple of questions that surface for me as I play with it:

1. When multiple filters are selected, there's no way to differentiate type of status in the results. Options I can think of include:
 - Creating separate sections w/ headers (probably clunkier to implement on the dev side)
 - Adding a `Status` tag in each card (a little time-consuming on the content side but no biggie to maintain once complete)
 - Visual differentiation between card types (perhaps using background color in the technology section). E.g. light green: ongoing, slightly darker green: active, light blue: inactive, slightly darker blue: complete, yellow or red: decommissioned). This could require more cognitive load on the user than it solves for, though, in order to grok the different meanings.
 
2. This approach loses the definitions and ways to get involved in each project type. Some approaches to resolve might include:
 - Revise the "Becoming an OpenOakland project" section to accommodate that info, too (eg "How to get involved")
 - Related to the first option in #1: section out the results with a preface.
 - ???

Definitely would love your thoughts!

**Comment by robdodson** [comment]
> When multiple filters are selected, there's no way to differentiate type of status in the results. Options I can think of include:

I was thinking about a combination of options 2 and 3 (a status badge + design tweak for cards). Currently the projects are organized into different yaml files for active/inactive/decommissioned, so the badge can be inferred from that.

> This approach loses the definitions and ways to get involved in each project type.

Yeah, I may spend some time this evening noodling on a solution for this.

**Comment by robdodson** [comment]
I added little status badges next to each project title

image

**Comment by robdodson** [comment]
I think I'm going to try creating a little section which explains the badge taxonomy. Hopefully it'll let us reuse the copy which explained the difference between active, inactive, and decommissioned projects.

**Comment by robdodson** [comment]
@theecrit I've updated this PR with a possible solution and wanted to get your thoughts.

The top of the project list has explanations for getting involved in active and ongoing projects.
I moved the inactive and decommissioned explainers down to the bottom of the "How to becomes a project section"
I also gave inactive and decommissioned projects a little link on their cards which jumps to the explainers:

image

**Pull request merged**
