### PR TITLE
Feat/js type styles

### LINKED ISSUE #111: Header navigation bar
#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

### PR DESCRIPTION
**Pull request by theecrit**
**Closes #111 and #115** 

### _Please describe the changes this PR makes_
- Changes header to full-width to allow better spacing of menu items.
- Adjusts universal type style to Open Sans (in compliance with OpenOakland Style Guide), and adjusts size and spacing across the board for improved readability.
- Minor white space tweaks for various elements (iframes, header logo)

### Mobile screenshots

[Home](https://user-images.githubusercontent.com/32755410/95690223-f3695d00-0bca-11eb-9ec2-adec10db1185.png) | [About](https://user-images.githubusercontent.com/32755410/95690225-ffedb580-0bca-11eb-967f-c33e782f768b.png) | [Resources](https://user-images.githubusercontent.com/32755410/95690233-0c720e00-0bcb-11eb-8ebc-8f9b7c6b1228.png)

### Desktop screenshots

[Home](https://user-images.githubusercontent.com/32755410/95690247-1bf15700-0bcb-11eb-8df1-c37c6195ecff.png) | [About](https://user-images.githubusercontent.com/32755410/95690252-23186500-0bcb-11eb-9051-a7df97071521.png) | [Resources](https://user-images.githubusercontent.com/32755410/95690259-2c093680-0bcb-11eb-8bae-a8735142dc8d.png)

### CODE REVIEW

**Comment by kwonangela7** [comment]
The changes look great Jess! (btw, congrats on locating the css file :)) 

Just noticed one thing:
- Can you add http://oakca.us/hack-night on the Home page? Right before the "Join us in Slack" it just says "You'll find us every Tuesday night on Zoom at ."

**Review by kwonangela7 — APPROVED** [review]
Just noticed one thing:

Can you add http://oakca.us/hack-night on the Home page? Right before the "Join us in Slack" it just says "You'll find us every Tuesday night on Zoom at ."

Doesn't seem like this is something you changed but if you could fix that real quick that would be great!!

**Comment by kwonangela7** [comment]
The changes look great Jess! (btw, congrats on locating the css file :))

I just left one content comment, but otherwise, I think you're free to merge! :)

**Comment by theecrit** [comment]
> Just noticed one thing:
> 
> Can you add http://oakca.us/hack-night on the Home page? Right before the "Join us in Slack" it just says "You'll find us every Tuesday night on Zoom at ."
> 
> Doesn't seem like this is something you changed but if you could fix that real quick that would be great!!

I'm going to add this as separate issue, as there are a couple of minor updates/corrections we can make here.

**Pull request merged**
